// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB38UP57_nAWrg_SWYcvkzwdECPH_jWKYY',
    appId: '1:908204182764:web:96bfbaed2d347afff2a9c9',
    messagingSenderId: '908204182764',
    projectId: 'biblioteca-7c40f',
    authDomain: 'biblioteca-7c40f.firebaseapp.com',
    storageBucket: 'biblioteca-7c40f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpY-YOjy3FM54zF7gHmEeHPvvX4whVYH4',
    appId: '1:908204182764:android:ba1c5b58f162f3baf2a9c9',
    messagingSenderId: '908204182764',
    projectId: 'biblioteca-7c40f',
    storageBucket: 'biblioteca-7c40f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFpuqhDIjJPrKBmSjsQfNPwqPOjNGlBXI',
    appId: '1:908204182764:ios:b9bb1a6b1a2d781ef2a9c9',
    messagingSenderId: '908204182764',
    projectId: 'biblioteca-7c40f',
    storageBucket: 'biblioteca-7c40f.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFpuqhDIjJPrKBmSjsQfNPwqPOjNGlBXI',
    appId: '1:908204182764:ios:b9bb1a6b1a2d781ef2a9c9',
    messagingSenderId: '908204182764',
    projectId: 'biblioteca-7c40f',
    storageBucket: 'biblioteca-7c40f.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB38UP57_nAWrg_SWYcvkzwdECPH_jWKYY',
    appId: '1:908204182764:web:ef07d3b48a1863d6f2a9c9',
    messagingSenderId: '908204182764',
    projectId: 'biblioteca-7c40f',
    authDomain: 'biblioteca-7c40f.firebaseapp.com',
    storageBucket: 'biblioteca-7c40f.firebasestorage.app',
  );
}
